### ISSUE TITLE
v0.32.0 Checklist

### ISSUE THREAD

**Issue by TheSriram** [awslabs/aws-sam-cli#1533]
## Checklist
- [x] sam deploy attempts to package every time, but relies on the idempotency of sam package. Lets separate those code paths.
- [x] add integration tests for package and deploy in single command
- [x] add integration tests for samconfig
- [x] Fix the `TestSamPython36HelloWorldIntegration::test_function_with_metadata` integ test that is failing in Windodws
- [x] `sam init` -> `sam build` -> `sam deploy <without s3-bucket arg>` fails when trying to package the template because it assumes a value for s3-bucket is always provided
- [x] `--use-json` flag in `sam deploy` seems irrelevant. Can we get rid of the parameter and make JSON the default?
- [x] Colors on sam deploy
- [x] Don't enable botocore Null Logger when `--debug` is specified

**Comment by jfuss** [comment]
I saw a lot of random failures yesterday spread throughout tests that run on Windows (not just `TestSamPython36HelloWorldIntegration::test_function_with_metadata`). We also need to figure out why some of the package regressions tests pass locally but not on appveyor. I can see what we can do there. I have also see random dotnet tests for build on windows fail. I can add some retry's there.

**Comment by TheSriram** [comment]
Release v0.33.1 is out.
